In [2]:
import numpy as np

In [3]:
n=int(input("Length:"))

li = [int(input("item : ")) for i in range(n)]

print(li)

arr = np.array(li)
print(arr)

[23, 12, 23, 14, 15]
[23 12 23 14 15]


In [4]:
arr.ndim

1

In [5]:
arr.shape

(5,)

In [6]:
arr.size

5

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(f"dim : {arr.ndim}")
print(f"size : {arr.size}")
print(f"shape : {arr.shape}")
print(f"{arr}")

dim : 2
size : 6
shape : (2, 3)
[[1 2 3]
 [4 5 6]]


In [9]:
# conversion of typo

arr=np.array([1, 2, 3, 4])
arr.dtype

dtype('int32')

In [ ]:
arr=np.array([1, 2, 4, 3], dtype="f4") # f4 -> typecode for float32
print(arr.dtype)

arr=np.array([1, 2, 4, 3], dtype="float32") # float32 -> type
print(arr.dtype)

float32
float32


In [13]:
arr = np.array([1, 2, 3, 4], dtype = "complex64")

print(arr)
print(arr.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex64


In [14]:
arr=np.array([[1+2j],[3+4j], [6+5j]])

print(arr)

print(arr.dtype)
print(type(arr))

[[1.+2.j]
 [3.+4.j]
 [6.+5.j]]
complex128
<class 'numpy.ndarray'>


In [16]:
arr=np.array([[1+2j],[3+4j], [6+5j]], dtype="complex64")

print(arr)

print(arr.dtype)
print(type(arr))

[[1.+2.j]
 [3.+4.j]
 [6.+5.j]]
complex64
<class 'numpy.ndarray'>


matrix works on loop

In [20]:
arr=np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


k : int, optional

  Index of the diagonal: 0 (the default) refers to the main diagonal, 
  
  a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

In [17]:
arr=np.eye(3, k=1)

print(arr)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [18]:
arr=np.eye(3, k=-1)

print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [21]:
arr=np.identity(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# x - axis observations -> # of rows
print(arr.shape[0])

# y - axis observations -> # of cols
print(arr.shape[1])

3
3


distribution